version: '3'

services:
  AdotaDatabase:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=adota_api_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
    # networks:
    #   - adota_api

volumes:
  postgres-data:

# networks:
#   adota_api:
#     driver: bridge


  